package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA



/**
 * AccessKey generated by hbm2java
 */
public class AccessKey  implements java.io.Serializable {


     private int userId;
     private String accessKey;

    public AccessKey() {
    }

    public AccessKey(int userId, String accessKey) {
       this.userId = userId;
       this.accessKey = accessKey;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getAccessKey() {
        return this.accessKey;
    }
    
    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey;
    }




}


