package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer id;
     private Integer translationId;
     private Integer translationContextId;
     private Integer userCreatesTrAccepId;
     private int userId;

    public Report() {
    }

	
    public Report(int userId) {
        this.userId = userId;
    }
    public Report(Integer translationId, Integer translationContextId, Integer userCreatesTrAccepId, int userId) {
       this.translationId = translationId;
       this.translationContextId = translationContextId;
       this.userCreatesTrAccepId = userCreatesTrAccepId;
       this.userId = userId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTranslationId() {
        return this.translationId;
    }
    
    public void setTranslationId(Integer translationId) {
        this.translationId = translationId;
    }
    public Integer getTranslationContextId() {
        return this.translationContextId;
    }
    
    public void setTranslationContextId(Integer translationContextId) {
        this.translationContextId = translationContextId;
    }
    public Integer getUserCreatesTrAccepId() {
        return this.userCreatesTrAccepId;
    }
    
    public void setUserCreatesTrAccepId(Integer userCreatesTrAccepId) {
        this.userCreatesTrAccepId = userCreatesTrAccepId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


