package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TranslationContext generated by hbm2java
 */
public class TranslationContext  implements java.io.Serializable {


     private Integer id;
     private Date creationDate;
     private int phrase1id;
     private int phrase2id;
     private int userId;
     private int translationId;

    public TranslationContext() {
    }

    public TranslationContext(Date creationDate, int phrase1id, int phrase2id, int userId, int translationId) {
       this.creationDate = creationDate;
       this.phrase1id = phrase1id;
       this.phrase2id = phrase2id;
       this.userId = userId;
       this.translationId = translationId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public int getPhrase1id() {
        return this.phrase1id;
    }
    
    public void setPhrase1id(int phrase1id) {
        this.phrase1id = phrase1id;
    }
    public int getPhrase2id() {
        return this.phrase2id;
    }
    
    public void setPhrase2id(int phrase2id) {
        this.phrase2id = phrase2id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getTranslationId() {
        return this.translationId;
    }
    
    public void setTranslationId(int translationId) {
        this.translationId = translationId;
    }




}


