package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Translation generated by hbm2java
 */
public class Translation  implements java.io.Serializable {


     private Integer id;
     private Date creationDate;
     private int userId;
     private int wla1Id;
     private int wla2Id;

    public Translation() {
    }

    public Translation(Date creationDate, int userId, int wla1Id, int wla2Id) {
       this.creationDate = creationDate;
       this.userId = userId;
       this.wla1Id = wla1Id;
       this.wla2Id = wla2Id;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getWla1Id() {
        return this.wla1Id;
    }
    
    public void setWla1Id(int wla1Id) {
        this.wla1Id = wla1Id;
    }
    public int getWla2Id() {
        return this.wla2Id;
    }
    
    public void setWla2Id(int wla2Id) {
        this.wla2Id = wla2Id;
    }




}


