package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Unsuscribed generated by hbm2java
 */
public class Unsuscribed  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private String feedback;
     private boolean banned;
     private Date unsuscriptionDate;

    public Unsuscribed() {
    }

	
    public Unsuscribed(int userId, boolean banned, Date unsuscriptionDate) {
        this.userId = userId;
        this.banned = banned;
        this.unsuscriptionDate = unsuscriptionDate;
    }
    public Unsuscribed(int userId, String feedback, boolean banned, Date unsuscriptionDate) {
       this.userId = userId;
       this.feedback = feedback;
       this.banned = banned;
       this.unsuscriptionDate = unsuscriptionDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public boolean isBanned() {
        return this.banned;
    }
    
    public void setBanned(boolean banned) {
        this.banned = banned;
    }
    public Date getUnsuscriptionDate() {
        return this.unsuscriptionDate;
    }
    
    public void setUnsuscriptionDate(Date unsuscriptionDate) {
        this.unsuscriptionDate = unsuscriptionDate;
    }




}


