package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserCreatesTrAccep generated by hbm2java
 */
public class UserCreatesTrAccep  implements java.io.Serializable {


     private Integer id;
     private int translationId;
     private int acceptationId;
     private int userId;
     private Date creationDate;

    public UserCreatesTrAccep() {
    }

    public UserCreatesTrAccep(int translationId, int acceptationId, int userId, Date creationDate) {
       this.translationId = translationId;
       this.acceptationId = acceptationId;
       this.userId = userId;
       this.creationDate = creationDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTranslationId() {
        return this.translationId;
    }
    
    public void setTranslationId(int translationId) {
        this.translationId = translationId;
    }
    public int getAcceptationId() {
        return this.acceptationId;
    }
    
    public void setAcceptationId(int acceptationId) {
        this.acceptationId = acceptationId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


