package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private Date registrationDate;
     private String ipAddressReg;
     private Boolean validated;
     private Integer languageId;
     private Integer roleId;
     private Integer defaultLangFrom;
     private Integer defaultLangTo;
     private Boolean invertAcceptations;
     private Boolean hideDefLangFrom;
     private Boolean hideDefLangTo;
     private Boolean autoAdding;
     private Boolean hideUsername;

    public User() {
    }

    public User(String username, String password, String email, Date registrationDate, String ipAddressReg, Boolean validated, Integer languageId, Integer roleId, Integer defaultLangFrom, Integer defaultLangTo, Boolean invertAcceptations, Boolean hideDefLangFrom, Boolean hideDefLangTo, Boolean autoAdding, Boolean hideUsername) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.registrationDate = registrationDate;
       this.ipAddressReg = ipAddressReg;
       this.validated = validated;
       this.languageId = languageId;
       this.roleId = roleId;
       this.defaultLangFrom = defaultLangFrom;
       this.defaultLangTo = defaultLangTo;
       this.invertAcceptations = invertAcceptations;
       this.hideDefLangFrom = hideDefLangFrom;
       this.hideDefLangTo = hideDefLangTo;
       this.autoAdding = autoAdding;
       this.hideUsername = hideUsername;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public String getIpAddressReg() {
        return this.ipAddressReg;
    }
    
    public void setIpAddressReg(String ipAddressReg) {
        this.ipAddressReg = ipAddressReg;
    }
    public Boolean getValidated() {
        return this.validated;
    }
    
    public void setValidated(Boolean validated) {
        this.validated = validated;
    }
    public Integer getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Integer getDefaultLangFrom() {
        return this.defaultLangFrom;
    }
    
    public void setDefaultLangFrom(Integer defaultLangFrom) {
        this.defaultLangFrom = defaultLangFrom;
    }
    public Integer getDefaultLangTo() {
        return this.defaultLangTo;
    }
    
    public void setDefaultLangTo(Integer defaultLangTo) {
        this.defaultLangTo = defaultLangTo;
    }
    public Boolean getInvertAcceptations() {
        return this.invertAcceptations;
    }
    
    public void setInvertAcceptations(Boolean invertAcceptations) {
        this.invertAcceptations = invertAcceptations;
    }
    public Boolean getHideDefLangFrom() {
        return this.hideDefLangFrom;
    }
    
    public void setHideDefLangFrom(Boolean hideDefLangFrom) {
        this.hideDefLangFrom = hideDefLangFrom;
    }
    public Boolean getHideDefLangTo() {
        return this.hideDefLangTo;
    }
    
    public void setHideDefLangTo(Boolean hideDefLangTo) {
        this.hideDefLangTo = hideDefLangTo;
    }
    public Boolean getAutoAdding() {
        return this.autoAdding;
    }
    
    public void setAutoAdding(Boolean autoAdding) {
        this.autoAdding = autoAdding;
    }
    public Boolean getHideUsername() {
        return this.hideUsername;
    }
    
    public void setHideUsername(Boolean hideUsername) {
        this.hideUsername = hideUsername;
    }




}


