package data.model;
// Generated 12-jun-2012 14:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Wla generated by hbm2java
 */
public class Wla  implements java.io.Serializable {


     private Integer id;
     private int wordLanguageId;
     private Integer acceptationId;
     private Date creationDate;
     private int userId;

    public Wla() {
    }

	
    public Wla(int wordLanguageId, Date creationDate, int userId) {
        this.wordLanguageId = wordLanguageId;
        this.creationDate = creationDate;
        this.userId = userId;
    }
    public Wla(int wordLanguageId, Integer acceptationId, Date creationDate, int userId) {
       this.wordLanguageId = wordLanguageId;
       this.acceptationId = acceptationId;
       this.creationDate = creationDate;
       this.userId = userId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getWordLanguageId() {
        return this.wordLanguageId;
    }
    
    public void setWordLanguageId(int wordLanguageId) {
        this.wordLanguageId = wordLanguageId;
    }
    public Integer getAcceptationId() {
        return this.acceptationId;
    }
    
    public void setAcceptationId(Integer acceptationId) {
        this.acceptationId = acceptationId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


